### PR TITLE
Create alias CARDS -> CONTRACTS

### PR DESCRIPTION
**Pull request by taromurao**
As a preparation of replacing uses of "card" with "contract", alias of core library's public interfaces were created.

### CODE REVIEW

**Comment by taromurao** [comment]
@balena-ci retest

**Review by Ereski — CHANGES_REQUESTED** [review]
LGTM. Only thing is that this PR introduces a minor change. Add `Change-type: minor` to the end of one of your commits.

Once the whole JF dependency situation is unmessified we can drop the deprecated symbols.

**Comment by taromurao** [comment]
I squashed commits and changed change-type tag from patch to minor.

**Comment by Ereski** [comment]
@taromurao that's not the right format. You need to add `Change-type: minor` to the end of the commit. Take a look at the commit history

**Comment by taromurao** [comment]
@Ereski OK. I just did it this way until now. I will switch to the footer format.

**Review by Ereski — APPROVED** [review]

**Comment by Ereski** [comment]
@taromurao A good next step would be the queue

**Comment by taromurao** [comment]
@Ereski Good advice. I will simply go for it.

**Pull request merged**
